on: [push, pull_request]

name: R-check

jobs:
  linux_check: 
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip linux')"
    env:
      GITHUB_PAT: ${{secrets.GH_PAT}}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
  
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
  
      - uses: r-lib/actions/check-r-package@v2
  winos_check: 
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip winos')"
    env:
      GITHUB_PAT: ${{secrets.GH_PAT}}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
  
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
  
      - uses: r-lib/actions/check-r-package@v2
  osx-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
  
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
  
      - uses: r-lib/actions/check-r-package@v2
    
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: covrpage
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'remotes::install_github("yonicd/covrpage")' \
                  -e 'covrpage::covrpage_ci()'
          git commit tests/README.md -m 'Update tests/README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_PAT}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - name: Deploy package
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'install.packages("pkgdown")' \
                  -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
